/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_melon_learn_jnilearning_JNIClass */

#ifndef _Included_com_melon_learn_jnilearning_JNIClass
#define _Included_com_melon_learn_jnilearning_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_melon_learn_jnilearning_JNIClass
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_melon_learn_jnilearning_JNIClass_getNativeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
